# -*- coding: utf-8 -*-
"""Data_Vizualization.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1eMg0zIEWj9h7qniOgVszSinpIw3g31Ui
"""

import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import plotly.express as px

df=pd.read_csv('/content/drive/MyDrive/NewHousing.csv')

df.head()

df.tail()

df.describe()

df.info()

df.columns

print("Some Statistics are:")
print(df['median_house_value'].describe())
print()
print("House price Medians are:")
print(df['median_house_value'].median())

"""#DATA CLEANING"""

df=df.drop_duplicates()

print(df.isnull().sum())

df.replace([np.inf, -np.inf], np.nan, inplace=True)

X = df["total_bedrooms"].mean()
df["total_bedrooms"].fillna(X,inplace=True)

print(df.isnull().sum())

df['longitude'] = df['longitude'].astype(float)
df['latitude'] = df['latitude'].astype(float)
df['housing_median_age'] = df['housing_median_age'].astype(int)
df['total_rooms'] = df['total_rooms'].astype(int)
df['total_bedrooms'] = df['total_bedrooms'].astype(float)
df['population'] = df['population'].astype(int)
df['households'] = df['households'].astype(int)
df['median_income'] = df['median_income'].astype(float)
df['median_house_value'] = df['median_house_value'].astype(int)

df['median_income'] = df['median_income'] / df['median_income'].max()

"""#Data Visalization"""

plt.scatter(df['median_income'], df['median_house_value'])
font1 = {'family':'serif','color':'blue','size':20}
font2 = {'family':'serif','color':'darkred','size':15}
plt.xlabel('Median Income->',fontdict = font2)
plt.ylabel('Median House Value->',fontdict = font2)
plt.title('Median House Value vs. Median Income',fontdict = font1)
plt.show()

plt.bar(df['ocean_proximity'].unique(), df['ocean_proximity'].value_counts())
plt.xlabel('Ocean Proximity->')
plt.ylabel('Frequency->')
plt.title('Distribution of Ocean Proximity')
plt.show

df['ocean_proximity'] = df['ocean_proximity'].map({'NEAR BAY': 0, '<1H OCEAN': 1, 'INLAND': 2, 'ISLAND': 3, 'NEAR OCEAN': 4})

corr_matrix = df.corr()

sns.set()
sns.heatmap(corr_matrix, annot=True, cmap='coolwarm', square=True)
plt.title('Correlation Matrix')
plt.show()

plt.boxplot(df['total_bedrooms'])
plt.xlabel('Total Bedrooms->',fontdict = font1)
plt.ylabel('Value->',fontdict = font1)
plt.title('Distribution of Total Bedrooms',fontdict = font2,loc = 'left')
plt.show()

fig = px.scatter(df, x='median_income', y='median_house_value')
fig.update_layout(title='Median House Value vs. Median Income', xaxis_title='Median Income', yaxis_title='Median House Value')
fig.show()

plt.hist(df['median_income'], bins=50)
plt.xlabel('Median Income->')
plt.ylabel('Frequency->')
plt.title('Histogram of Median Income')
plt.show()
plt.hist(df['total_bedrooms'], bins=50)
plt.xlabel('Total Bedrooms->')
plt.ylabel('Frequency->')
plt.title('Histogram of Total Bedrooms')
plt.show()